import type { AccountMappingResult, AccountMappingRule } from "./types";

type StatementContext = "balance_sheet" | "income_statement" | "fixed_asset";

const balanceSheetCategories = new Set([
  "TOTAL_ASSETS",
  "CURRENT_ASSET",
  "CASH_ON_HAND",
  "CASH_ON_BANK",
  "ACCOUNT_RECEIVABLE",
  "EMPLOYEE_RECEIVABLE",
  "INVENTORY",
  "FIXED_ASSET",
  "FIXED_ASSET_ACQUISITION",
  "ACCUMULATED_DEPRECIATION",
  "INTANGIBLE_ASSETS",
  "NON_CURRENT_ASSET",
  "TOTAL_LIABILITIES",
  "CURRENT_LIABILITIES",
  "BANK_LOAN_SHORT_TERM",
  "ACCOUNT_PAYABLE",
  "TAX_PAYABLE",
  "OTHER_PAYABLE",
  "BANK_LOAN_LONG_TERM",
  "NON_CURRENT_LIABILITIES",
  "MODAL_DISETOR",
  "PENAMBAHAN_MODAL_DISETOR",
  "RETAINED_EARNINGS_SURPLUS",
  "RETAINED_EARNINGS_CURRENT_PROFIT",
  "NON_OPERATING_FIXED_ASSETS",
  "EXCESS_CASH",
  "MARKETABLE_SECURITIES",
  "INTEREST_PAYABLE",
  "INTEREST_BEARING_DEBT",
  "SURPLUS_ASSET_CASH",
]);

const incomeStatementCategories = new Set([
  "REVENUE",
  "COST_OF_GOOD_SOLD",
  "SELLING_EXPENSE",
  "GENERAL_ADMINISTRATIVE_OVERHEADS",
  "OPERATING_EXPENSE",
  "DEPRECIATION_EXPENSE",
  "EBIT",
  "COMMERCIAL_NPAT",
  "CORPORATE_TAX",
  "INTEREST_INCOME",
  "INTEREST_EXPENSE",
  "NON_OPERATING_INCOME",
]);

const fixedAssetCategories = new Set(["FIXED_ASSET", "FIXED_ASSET_ACQUISITION", "ACCUMULATED_DEPRECIATION", "DEPRECIATION_EXPENSE"]);

const statementAgnosticCategories = new Set([
  "WORKING_CAPITAL",
  "CASH_FLOW_FROM_FINANCING",
  "CASH_FLOW_FROM_OPERATIONS",
  "CASH_FLOW_FROM_NON_OPERATIONS",
  "CASH_FLOW_AVAILABLE_TO_INVESTOR",
]);

export const accountMappingRules: AccountMappingRule[] = [
  {
    category: "TOTAL_ASSETS",
    displayName: "Total Assets",
    aliases: ["total assets", "jumlah aset", "total aset", "total aktiva", "jumlah aktiva"],
    includeKeywords: ["total assets", "jumlah aset", "total aset", "total aktiva", "jumlah aktiva", "assets", "aktiva"],
    treatment: "review",
    valuationImpact: ["AAM"],
    reviewNote: "Gunakan sebagai override total assets hanya jika rincian komponen asset tidak tersedia atau sudah direkonsiliasi.",
  },
  {
    category: "CURRENT_ASSET",
    displayName: "Current Asset",
    aliases: [
      "current asset",
      "current assets",
      "aset lancar",
      "aktiva lancar",
      "aset lancar lainnya",
      "other current assets",
      "prepaid expenses",
      "biaya dibayar dimuka",
      "beban dibayar dimuka",
      "uang muka",
      "pajak dibayar dimuka",
      "ppn masukan",
      "contract asset",
      "aset kontrak",
    ],
    includeKeywords: [
      "current asset",
      "current assets",
      "aset lancar",
      "aktiva lancar",
      "lancar",
      "current",
      "prepaid",
      "dibayar dimuka",
      "uang muka",
      "ppn masukan",
      "contract asset",
      "aset kontrak",
    ],
    excludeKeywords: ["non current", "non-current", "noncurrent", "tidak lancar", "non lancar"],
    treatment: "review",
    valuationImpact: ["AAM", "working capital support"],
    reviewNote: "Petakan ke kategori current asset yang lebih rinci jika subledger tersedia; prepaid dan contract asset perlu tinjauan operating WC.",
  },
  {
    category: "CASH_ON_HAND",
    displayName: "Cash on Hand",
    aliases: ["cash on hand", "cash on hands", "kas", "kas kecil", "uang kas", "kas di tangan", "kas tunai"],
    includeKeywords: ["cash on hand", "kas kecil", "uang kas", "kas tunai", "cash", "kas"],
    excludeKeywords: ["bank", "deposito", "deposit"],
    treatment: "review",
    valuationImpact: ["AAM", "surplus asset sensitivity", "minimum operating cash"],
    reviewNote: "Cash on hand dapat menjadi operating cash; tinjau minimum operating cash sebelum seluruhnya diperlakukan sebagai surplus.",
  },
  {
    category: "CASH_ON_BANK",
    displayName: "Cash on Bank / Deposit",
    aliases: [
      "cash on bank",
      "cash at bank",
      "cash and cash equivalents",
      "kas dan setara kas",
      "bank",
      "deposito",
      "deposit",
      "time deposit",
      "deposito berjangka",
      "giro",
      "rekening bank",
      "kas bank",
      "bank danamon",
    ],
    includeKeywords: [
      "cash on bank",
      "cash at bank",
      "cash equivalents",
      "kas dan setara kas",
      "rekening bank",
      "kas bank",
      "bank",
      "deposito",
      "deposit",
      "time deposit",
      "giro",
    ],
    excludeKeywords: ["utang", "hutang", "pinjaman", "loan", "liabilitas", "kewajiban", "payable"],
    treatment: "non_operating",
    valuationImpact: ["AAM", "EEM bridge", "DCF bridge", "marketable securities review"],
    reviewNote: "Pisahkan operating bank account dari deposit/investment jika subledger tersedia.",
  },
  {
    category: "EXCESS_CASH",
    displayName: "Excess Cash",
    aliases: ["excess cash", "kas berlebih", "kelebihan kas", "cash surplus operasi"],
    includeKeywords: ["excess", "berlebih", "kelebihan", "surplus"],
    treatment: "non_operating",
    valuationImpact: ["EEM bridge", "DCF bridge", "surplus asset sensitivity"],
    reviewNote: "Perlakukan sebagai non-operating hanya setelah minimum operating cash dipertimbangkan.",
  },
  {
    category: "SURPLUS_ASSET_CASH",
    displayName: "Surplus Asset Cash",
    aliases: ["surplus asset cash", "kas surplus", "surplus kas", "kas non operasional"],
    includeKeywords: ["surplus", "kas", "cash", "non operasional"],
    treatment: "non_operating",
    valuationImpact: ["EEM bridge", "DCF bridge"],
    reviewNote: "Cash-like surplus asset ditambahkan pada EV-to-equity bridge setelah tinjauan operating cash.",
  },
  {
    category: "MARKETABLE_SECURITIES",
    displayName: "Marketable Securities",
    aliases: [
      "marketable securities",
      "surat berharga",
      "efek",
      "investasi jangka pendek",
      "deposito investasi",
      "financial assets at fair value",
      "aset keuangan diukur pada nilai wajar",
      "fair value through profit or loss",
      "fvpl",
      "obligasi",
      "saham diperdagangkan",
      "reksa dana",
    ],
    includeKeywords: [
      "surat berharga",
      "marketable securities",
      "marketable",
      "securities",
      "efek",
      "investasi jangka pendek",
      "financial assets",
      "nilai wajar",
      "fair value",
      "fvpl",
      "obligasi",
      "reksa dana",
    ],
    treatment: "non_operating",
    valuationImpact: ["AAM", "EEM bridge", "DCF bridge"],
    reviewNote: "Umumnya non-operating kecuali dibutuhkan untuk ordinary operations.",
  },
  {
    category: "ACCOUNT_RECEIVABLE",
    displayName: "Account Receivable",
    aliases: [
      "account receivable",
      "accounts receivable",
      "piutang usaha",
      "piutang dagang",
      "trade receivable",
      "receivable",
      "trade and other receivables",
      "piutang pelanggan",
      "piutang customer",
      "piutang dari pelanggan",
      "contract receivable",
      "retention receivable",
      "piutang retensi",
    ],
    includeKeywords: [
      "account receivable",
      "accounts receivable",
      "piutang usaha",
      "piutang dagang",
      "trade receivable",
      "piutang pelanggan",
      "contract receivable",
      "retention receivable",
      "piutang retensi",
      "piutang",
      "receivable",
    ],
    excludeKeywords: ["karyawan", "pegawai", "employee", "afiliasi", "berelasi", "shareholder", "pemegang saham"],
    treatment: "operating",
    valuationImpact: ["AAM", "working capital", "DCF WC days"],
    reviewNote: "Operating current asset kecuali bukti menunjukkan non-operating receivable.",
  },
  {
    category: "EMPLOYEE_RECEIVABLE",
    displayName: "Employee / Related Party Receivable",
    aliases: [
      "employee receivable",
      "piutang karyawan",
      "piutang pegawai",
      "pinjaman karyawan",
      "pinjaman pegawai",
      "due from related parties",
      "piutang pihak berelasi",
      "piutang afiliasi",
      "piutang pemegang saham",
      "pinjaman direksi",
      "pinjaman komisaris",
    ],
    includeKeywords: [
      "employee receivable",
      "piutang karyawan",
      "piutang pegawai",
      "pinjaman karyawan",
      "pinjaman pegawai",
      "due from related parties",
      "pihak berelasi",
      "afiliasi",
      "pemegang saham",
      "direksi",
      "komisaris",
      "karyawan",
      "pegawai",
      "employee",
    ],
    treatment: "non_operating",
    valuationImpact: ["AAM", "non-operating asset bridge"],
    reviewNote: "Umumnya dikeluarkan dari operating working capital dan ditambahkan sebagai non-operating asset.",
  },
  {
    category: "INVENTORY",
    displayName: "Inventory",
    aliases: [
      "inventory",
      "inventories",
      "persediaan",
      "stock",
      "stok",
      "barang persediaan",
      "raw materials",
      "bahan baku",
      "work in process",
      "work in progress",
      "barang dalam proses",
      "finished goods",
      "barang jadi",
      "supplies",
      "spare parts",
      "suku cadang",
    ],
    includeKeywords: [
      "inventory",
      "inventories",
      "persediaan",
      "stock",
      "stok",
      "barang persediaan",
      "raw materials",
      "bahan baku",
      "work in process",
      "work in progress",
      "barang dalam proses",
      "finished goods",
      "barang jadi",
      "supplies",
      "spare parts",
      "suku cadang",
    ],
    treatment: "operating",
    valuationImpact: ["AAM", "working capital", "DCF WC days"],
    reviewNote: "Operating current asset untuk working capital kecuali ada bukti obsolete/non-operating.",
  },
  {
    category: "FIXED_ASSET",
    displayName: "Fixed Asset",
    aliases: [
      "fixed asset",
      "fixed assets",
      "property plant and equipment",
      "ppe",
      "aset tetap",
      "aktiva tetap",
      "bangunan mess",
      "inventaris bangunan mess",
      "invt bangunan mess",
      "kendaraan",
      "alat berat",
      "tanah",
      "lahan sawit",
      "mesin",
      "peralatan",
      "furniture and fixtures",
      "perabot kantor",
      "right of use asset",
      "aset hak guna",
      "rou asset",
      "leasehold improvement",
    ],
    includeKeywords: [
      "fixed asset",
      "fixed assets",
      "property plant and equipment",
      "ppe",
      "aset tetap",
      "aktiva tetap",
      "bangunan",
      "inventaris",
      "kendaraan",
      "tanah",
      "lahan",
      "alat berat",
      "mesin",
      "peralatan",
      "furniture",
      "perabot",
      "right of use",
      "hak guna",
      "rou",
      "leasehold",
    ],
    excludeKeywords: ["perolehan", "acquisition", "purchase", "pembelian", "harga"],
    treatment: "operating",
    valuationImpact: ["AAM", "EEM NTA", "DCF invested capital"],
    reviewNote: "Perlakukan sebagai operating kecuali ada bukti idle atau non-operating fixed assets.",
  },
  {
    category: "NON_OPERATING_FIXED_ASSETS",
    displayName: "Non-Operating Fixed Assets",
    aliases: [
      "non operating fixed assets",
      "aset tetap non operasional",
      "aktiva tetap non operasional",
      "aset idle",
      "idle asset",
      "investment property",
      "properti investasi",
      "asset held for sale",
      "aset dimiliki untuk dijual",
      "non current asset held for sale",
    ],
    includeKeywords: [
      "non operating",
      "non operasional",
      "idle",
      "investment property",
      "properti investasi",
      "held for sale",
      "dimiliki untuk dijual",
    ],
    treatment: "non_operating",
    valuationImpact: ["AAM", "EEM bridge", "DCF bridge"],
    reviewNote: "Tambahkan di luar operating NTA jika asset idle atau tidak diperlukan untuk earning power.",
  },
  {
    category: "FIXED_ASSET_ACQUISITION",
    displayName: "Fixed Asset Acquisition",
    aliases: ["harga perolehan", "acquisition cost", "purchase fixed asset", "pembelian aset tetap", "perolehan aset tetap", "nilai perolehan aset tetap"],
    includeKeywords: ["harga perolehan", "acquisition cost", "perolehan aset tetap", "perolehan", "acquisition", "purchase", "pembelian"],
    treatment: "operating",
    valuationImpact: ["fixed asset schedule", "AAM support", "DCF capex support"],
    reviewNote: "Gunakan bersama accumulated depreciation untuk menurunkan fixed asset net value jika net value tidak tersedia.",
  },
  {
    category: "ACCUMULATED_DEPRECIATION",
    displayName: "Accumulated Depreciation",
    aliases: ["accumulated depreciation", "akumulasi penyusutan", "akumulasi depresiasi", "acc dep", "akm penyusutan"],
    includeKeywords: ["accumulated depreciation", "akumulasi penyusutan", "akumulasi depresiasi", "akumulasi", "accumulated"],
    treatment: "operating",
    valuationImpact: ["fixed asset schedule", "AAM support", "EEM NTA support"],
    reviewNote: "Kurangkan dari acquisition cost jika fixed asset net value tidak tersedia langsung.",
  },
  {
    category: "DEPRECIATION_EXPENSE",
    displayName: "Depreciation Expense",
    aliases: ["depreciation expense", "depreciation", "depresiasi", "beban penyusutan", "biaya penyusutan", "beban depresiasi", "biaya depresiasi", "penyusutan"],
    includeKeywords: ["depreciation expense", "beban penyusutan", "biaya penyusutan", "beban depresiasi", "biaya depresiasi", "penyusutan", "depreciation", "depresiasi"],
    excludeKeywords: ["akumulasi", "accumulated"],
    treatment: "operating",
    valuationImpact: ["EBIT", "DCF depreciation margin"],
    reviewNote: "Operating non-cash expense untuk EBIT dan proxy DCF maintenance capex.",
  },
  {
    category: "INTANGIBLE_ASSETS",
    displayName: "Intangible Assets",
    aliases: [
      "intangible assets",
      "aset tak berwujud",
      "aktiva tak berwujud",
      "software",
      "hak guna",
      "license",
      "licence",
      "lisensi",
      "goodwill",
      "merek dagang",
      "trademark",
      "brand",
      "patent",
      "paten",
      "customer relationship",
    ],
    includeKeywords: [
      "tak berwujud",
      "intangible",
      "software",
      "license",
      "licence",
      "lisensi",
      "goodwill",
      "merek",
      "trademark",
      "brand",
      "patent",
      "paten",
      "customer relationship",
    ],
    treatment: "review",
    valuationImpact: ["AAM", "NTA exclusion review"],
    reviewNote: "Akui untuk AAM, tetapi tinjau pengecualian dari tangible operating asset base untuk EEM.",
  },
  {
    category: "NON_CURRENT_ASSET",
    displayName: "Non-Current Asset",
    aliases: [
      "non current asset",
      "non current assets",
      "non-current asset",
      "non-current assets",
      "noncurrent asset",
      "noncurrent assets",
      "aset tidak lancar",
      "aktiva tidak lancar",
      "other non current assets",
      "aset tidak lancar lainnya",
      "long term investment",
      "investasi jangka panjang",
      "investment in associates",
      "investasi pada entitas asosiasi",
      "investment in joint venture",
      "deferred tax asset",
      "aset pajak tangguhan",
      "refundable deposit",
      "security deposit",
      "uang jaminan",
      "biological assets",
      "aset biologis",
      "bearer plants",
      "tanaman produktif",
    ],
    includeKeywords: [
      "non current asset",
      "non current assets",
      "non-current asset",
      "non-current assets",
      "noncurrent asset",
      "noncurrent assets",
      "aset tidak lancar",
      "aktiva tidak lancar",
      "investasi jangka panjang",
      "investment in associates",
      "entitas asosiasi",
      "joint venture",
      "deferred tax asset",
      "aset pajak tangguhan",
      "security deposit",
      "uang jaminan",
      "biological assets",
      "aset biologis",
      "bearer plants",
      "tanaman produktif",
    ],
    treatment: "review",
    valuationImpact: ["AAM", "non-operating asset review", "EEM NTA review"],
    reviewNote: "Non-current asset broad category; tentukan operating, surplus, atau excluded asset berdasarkan substansi dan bukti penggunaan.",
  },
  {
    category: "TOTAL_LIABILITIES",
    displayName: "Total Liabilities",
    aliases: ["total liabilities", "jumlah kewajiban", "total kewajiban", "total liabilitas", "jumlah liabilitas"],
    includeKeywords: ["total liabilities", "jumlah kewajiban", "total kewajiban", "total liabilitas", "jumlah liabilitas", "liabilities"],
    treatment: "liability",
    valuationImpact: ["AAM"],
    reviewNote: "Gunakan sebagai override total liabilities hanya jika rincian komponen liability tidak tersedia atau sudah direkonsiliasi.",
  },
  {
    category: "CURRENT_LIABILITIES",
    displayName: "Current Liabilities",
    aliases: [
      "current liabilities",
      "kewajiban lancar",
      "liabilitas lancar",
      "current portion of long term debt",
      "bagian lancar utang jangka panjang",
      "contract liability",
      "liabilitas kontrak",
      "deferred revenue",
      "pendapatan diterima dimuka",
      "unearned revenue",
      "uang muka pelanggan",
    ],
    includeKeywords: [
      "current liabilities",
      "kewajiban lancar",
      "liabilitas lancar",
      "current portion",
      "bagian lancar",
      "contract liability",
      "liabilitas kontrak",
      "deferred revenue",
      "pendapatan diterima dimuka",
      "unearned revenue",
      "uang muka pelanggan",
    ],
    treatment: "liability",
    valuationImpact: ["AAM", "working capital support"],
    reviewNote: "Petakan ke kategori liability yang lebih rinci jika subledger tersedia; contract liability dan customer advances umumnya operating.",
  },
  {
    category: "ACCOUNT_PAYABLE",
    displayName: "Account Payable",
    aliases: [
      "account payable",
      "account payables",
      "accounts payable",
      "accounts payables",
      "utang usaha",
      "hutang usaha",
      "utang dagang",
      "hutang dagang",
      "trade payable",
      "supplier payable",
      "utang pemasok",
      "hutang pemasok",
      "payable to suppliers",
    ],
    includeKeywords: [
      "account payable",
      "account payables",
      "accounts payable",
      "accounts payables",
      "utang usaha",
      "hutang usaha",
      "utang dagang",
      "hutang dagang",
      "trade payable",
      "supplier payable",
      "utang pemasok",
      "hutang pemasok",
      "payable to suppliers",
      "payables",
      "payable",
    ],
    excludeKeywords: ["bank", "loan", "pinjaman", "bunga", "interest", "tax", "pajak", "sewa", "lease"],
    treatment: "operating",
    valuationImpact: ["AAM", "working capital", "DCF WC days"],
    reviewNote: "Operating current liability untuk working capital.",
  },
  {
    category: "TAX_PAYABLE",
    displayName: "Tax Payable",
    aliases: [
      "tax payable",
      "taxes payable",
      "utang pajak",
      "hutang pajak",
      "pajak terutang",
      "income tax payable",
      "corporate income tax payable",
      "pph pasal 29",
      "pph 21",
      "pph 23",
      "pph 25",
      "pph 26",
      "pph final",
      "ppn",
      "ppn keluaran",
      "vat payable",
    ],
    includeKeywords: [
      "tax payable",
      "taxes payable",
      "income tax payable",
      "utang pajak",
      "hutang pajak",
      "pajak terutang",
      "pajak",
      "tax",
      "pph",
      "ppn",
      "vat payable",
      "ppn keluaran",
    ],
    treatment: "liability",
    valuationImpact: ["AAM", "debt-like sensitivity"],
    reviewNote: "Liability untuk AAM; keluarkan dari operating WC kecuali ada justifikasi khusus.",
  },
  {
    category: "OTHER_PAYABLE",
    displayName: "Other Payable",
    aliases: [
      "other payable",
      "utang lain-lain",
      "hutang lain-lain",
      "utang lainnya",
      "hutang lainnya",
      "accrued expense",
      "accrued expenses",
      "biaya masih harus dibayar",
      "beban masih harus dibayar",
      "salary payable",
      "utang gaji",
      "bonus payable",
      "jaminan pelanggan",
      "deposit pelanggan",
      "customer deposit",
      "royalty payable",
    ],
    includeKeywords: [
      "other payable",
      "utang lain",
      "hutang lain",
      "utang lainnya",
      "hutang lainnya",
      "accrued",
      "masih harus dibayar",
      "salary payable",
      "utang gaji",
      "bonus payable",
      "jaminan pelanggan",
      "deposit pelanggan",
      "customer deposit",
      "royalty payable",
    ],
    excludeKeywords: ["bank", "loan", "pinjaman", "tax", "pajak", "lease", "sewa", "interest", "bunga"],
    treatment: "operating",
    valuationImpact: ["AAM", "working capital", "DCF WC days"],
    reviewNote: "Tinjau apakah merupakan operating payable atau debt-like payable.",
  },
  {
    category: "BANK_LOAN_SHORT_TERM",
    displayName: "Bank Loan - Short Term",
    aliases: [
      "bank loan short term",
      "short term bank loan",
      "pinjaman bank jangka pendek",
      "utang bank jangka pendek",
      "hutang bank jangka pendek",
      "bank overdraft",
      "cerukan bank",
      "revolving loan",
      "kredit modal kerja",
      "kmk",
    ],
    includeKeywords: [
      "bank loan short term",
      "short term bank loan",
      "pinjaman bank jangka pendek",
      "utang bank jangka pendek",
      "hutang bank jangka pendek",
      "bank overdraft",
      "cerukan bank",
      "revolving loan",
      "kredit modal kerja",
      "kmk",
      "short term loan",
      "jangka pendek",
    ],
    treatment: "debt",
    valuationImpact: ["interest bearing debt", "EV to equity bridge"],
    reviewNote: "Keluarkan dari operating working capital; kurangkan sebagai debt jika saldo tidak nol.",
  },
  {
    category: "BANK_LOAN_LONG_TERM",
    displayName: "Bank Loan - Long Term",
    aliases: [
      "bank loan long term",
      "long term bank loan",
      "pinjaman bank jangka panjang",
      "utang bank jangka panjang",
      "hutang bank jangka panjang",
      "investment loan",
      "kredit investasi",
      "term loan",
    ],
    includeKeywords: [
      "bank loan long term",
      "long term bank loan",
      "pinjaman bank jangka panjang",
      "utang bank jangka panjang",
      "hutang bank jangka panjang",
      "investment loan",
      "kredit investasi",
      "term loan",
      "long term loan",
      "jangka panjang",
    ],
    treatment: "debt",
    valuationImpact: ["interest bearing debt", "EV to equity bridge"],
    reviewNote: "Keluarkan dari operating working capital; kurangkan sebagai debt jika saldo tidak nol.",
  },
  {
    category: "INTEREST_PAYABLE",
    displayName: "Interest Payable",
    aliases: ["interest payable", "utang bunga", "hutang bunga", "bunga masih harus dibayar", "bunga pinjaman masih harus dibayar", "accrued interest"],
    includeKeywords: ["bunga", "interest", "harus dibayar", "accrued"],
    treatment: "liability",
    valuationImpact: ["AAM", "debt-like liability review"],
    reviewNote: "Liability item; tinjau apakah perlu dimasukkan dalam debt-like adjustments.",
  },
  {
    category: "INTEREST_BEARING_DEBT",
    displayName: "Interest-Bearing Debt",
    aliases: [
      "interest bearing debt",
      "interest-bearing debt",
      "utang berbunga",
      "hutang berbunga",
      "pinjaman berbunga",
      "notes payable",
      "medium term notes",
      "obligasi",
      "bonds payable",
      "liabilitas sewa",
      "lease liability",
      "finance lease liability",
      "sewa pembiayaan",
      "sukuk",
    ],
    includeKeywords: [
      "berbunga",
      "interest bearing",
      "pinjaman berbunga",
      "notes payable",
      "medium term notes",
      "obligasi",
      "bonds payable",
      "liabilitas sewa",
      "lease liability",
      "finance lease",
      "sewa pembiayaan",
      "sukuk",
    ],
    treatment: "debt",
    valuationImpact: ["EV to equity bridge"],
    reviewNote: "Debt-like financing balance; keluarkan dari operating working capital.",
  },
  {
    category: "NON_CURRENT_LIABILITIES",
    displayName: "Non-Current Liabilities",
    aliases: [
      "non current liabilities",
      "non-current liabilities",
      "liabilitas tidak lancar",
      "kewajiban tidak lancar",
      "other non current liabilities",
      "liabilitas tidak lancar lainnya",
      "deferred tax liability",
      "liabilitas pajak tangguhan",
      "employee benefit liability",
      "liabilitas imbalan kerja",
      "post employment benefit obligation",
      "provision",
      "provisions",
      "provisi",
      "long term payable",
      "utang jangka panjang lainnya",
    ],
    includeKeywords: [
      "non current liabilities",
      "non-current liabilities",
      "liabilitas tidak lancar",
      "kewajiban tidak lancar",
      "deferred tax liability",
      "liabilitas pajak tangguhan",
      "employee benefit",
      "imbalan kerja",
      "post employment",
      "provision",
      "provisi",
      "long term payable",
      "utang jangka panjang lainnya",
    ],
    treatment: "liability",
    valuationImpact: ["AAM", "debt-like liability review"],
    reviewNote: "Non-current liability broad category; tinjau apakah bersifat operating, provision, deferred tax, atau debt-like.",
  },
  {
    category: "MODAL_DISETOR",
    displayName: "Modal Disetor",
    aliases: ["modal disetor", "paid up capital", "paid-up capital", "share capital", "capital stock"],
    includeKeywords: ["modal", "disetor", "capital"],
    excludeKeywords: ["penambahan", "additional", "agio"],
    treatment: "equity",
    valuationImpact: ["balance sheet check", "equity roll-forward"],
    reviewNote: "Equity component untuk rekonsiliasi; jangan gunakan sebagai enterprise-to-equity bridge item.",
  },
  {
    category: "PENAMBAHAN_MODAL_DISETOR",
    displayName: "Penambahan Modal Disetor",
    aliases: ["penambahan modal disetor", "additional paid in capital", "additional paid-in capital", "agio saham"],
    includeKeywords: ["penambahan", "additional", "agio"],
    treatment: "equity",
    valuationImpact: ["balance sheet check", "equity roll-forward"],
    reviewNote: "Equity component; perlakuan cash-flow sebaiknya memakai movement periode, bukan ending balance.",
  },
  {
    category: "RETAINED_EARNINGS_SURPLUS",
    displayName: "Retained Earnings Surplus",
    aliases: ["retained earnings surplus", "saldo laba", "laba ditahan"],
    includeKeywords: ["retained", "saldo laba", "laba ditahan"],
    treatment: "equity",
    valuationImpact: ["balance sheet check"],
    reviewNote: "Equity reconciliation account; bukan operating earning-power driver.",
  },
  {
    category: "RETAINED_EARNINGS_CURRENT_PROFIT",
    displayName: "Retained Earnings Current Profit",
    aliases: ["retained earnings current profit", "laba tahun berjalan", "laba periode berjalan"],
    includeKeywords: ["laba", "berjalan", "current profit"],
    treatment: "equity",
    valuationImpact: ["balance sheet check", "commercial/fiscal basis review"],
    reviewNote: "Tinjau basis commercial versus fiscal sebelum digunakan sebagai earning power.",
  },
  {
    category: "REVENUE",
    displayName: "Revenue",
    aliases: [
      "revenue",
      "sales",
      "net sales",
      "operating revenue",
      "penjualan",
      "penjualan bersih",
      "pendapatan",
      "pendapatan usaha",
      "pendapatan operasional",
      "penghasilan",
      "penghasilan usaha",
      "penghasilan operasional",
      "omzet",
      "omset",
      "peredaran usaha",
      "service revenue",
      "pendapatan jasa",
      "contract revenue",
      "pendapatan kontrak",
      "rental revenue",
      "pendapatan sewa",
      "net revenue",
      "gross revenue",
    ],
    includeKeywords: [
      "revenue",
      "sales",
      "net sales",
      "operating revenue",
      "penjualan",
      "penjualan bersih",
      "pendapatan usaha",
      "pendapatan operasional",
      "penghasilan usaha",
      "penghasilan operasional",
      "pendapatan",
      "penghasilan",
      "omzet",
      "omset",
      "peredaran usaha",
      "service revenue",
      "pendapatan jasa",
      "contract revenue",
      "pendapatan kontrak",
      "rental revenue",
      "pendapatan sewa",
      "net revenue",
      "gross revenue",
    ],
    excludeKeywords: ["beban", "biaya", "expense", "cost", "pokok", "interest", "bunga", "lain", "other", "non operating", "jasa giro", "deposito"],
    treatment: "operating",
    valuationImpact: ["DCF forecast driver", "margins"],
    reviewNote: "Gunakan commercial revenue sebagai operating driver.",
  },
  {
    category: "COST_OF_GOOD_SOLD",
    displayName: "Cost of Good Sold",
    aliases: [
      "cost of good sold",
      "cost of goods sold",
      "cost of revenue",
      "cost of sales",
      "cogs",
      "hpp",
      "beban pokok penjualan",
      "beban pokok pendapatan",
      "beban pokok",
      "harga pokok penjualan",
      "harga pokok",
      "direct costs",
      "biaya langsung",
      "bahan baku",
      "tenaga kerja langsung",
      "factory overhead",
      "overhead pabrik",
      "cost of services",
      "beban jasa",
      "pupuk",
      "obat-obatan",
      "tbs",
    ],
    includeKeywords: [
      "cost of good sold",
      "cost of goods sold",
      "cost of revenue",
      "cost of sales",
      "cogs",
      "hpp",
      "beban pokok",
      "harga pokok",
      "direct costs",
      "biaya langsung",
      "bahan baku",
      "tenaga kerja langsung",
      "factory overhead",
      "overhead pabrik",
      "cost of services",
      "beban jasa",
      "pokok",
      "pupuk",
      "obat",
      "tbs",
    ],
    treatment: "operating",
    valuationImpact: ["EBIT", "DCF margin"],
    reviewNote: "Operating cost; pertahankan sign convention secara konsisten.",
  },
  {
    category: "SELLING_EXPENSE",
    displayName: "Selling Expense",
    aliases: [
      "selling expense",
      "sales expense",
      "selling and distribution expense",
      "beban penjualan",
      "biaya penjualan",
      "beban pemasaran",
      "biaya pemasaran",
      "marketing expense",
      "advertising expense",
      "beban iklan",
      "komisi penjualan",
      "sales commission",
      "freight out",
      "ongkos kirim penjualan",
      "selling",
    ],
    includeKeywords: [
      "selling expense",
      "sales expense",
      "selling and distribution",
      "beban penjualan",
      "biaya penjualan",
      "beban pemasaran",
      "biaya pemasaran",
      "marketing",
      "advertising",
      "iklan",
      "komisi penjualan",
      "sales commission",
      "freight out",
      "ongkos kirim penjualan",
      "selling",
    ],
    excludeKeywords: ["revenue", "sales", "pendapatan"],
    treatment: "operating",
    valuationImpact: ["EBIT", "DCF margin"],
    reviewNote: "Operating expense; pertahankan sign convention secara konsisten.",
  },
  {
    category: "GENERAL_ADMINISTRATIVE_OVERHEADS",
    displayName: "General & Administrative Overheads",
    aliases: [
      "general administrative overheads",
      "general and administrative",
      "g&a",
      "administrasi",
      "beban administrasi",
      "biaya administrasi",
      "beban umum",
      "biaya umum",
      "general expenses",
      "administrative expenses",
      "office expenses",
      "professional fees",
      "jasa profesional",
      "legal fee",
      "audit fee",
      "rent expense",
      "beban sewa",
      "utilities",
      "listrik",
      "telepon",
      "internet",
      "insurance expense",
      "beban asuransi",
      "repair and maintenance",
      "perbaikan dan pemeliharaan",
      "travel expense",
      "perjalanan dinas",
      "overheads",
      "bbm",
      "stnk",
      "pbb",
      "notaris",
    ],
    includeKeywords: [
      "general administrative",
      "general and administrative",
      "g&a",
      "beban administrasi",
      "biaya administrasi",
      "beban umum",
      "biaya umum",
      "general expenses",
      "administrative expenses",
      "office expenses",
      "professional fees",
      "jasa profesional",
      "legal fee",
      "audit fee",
      "rent expense",
      "beban sewa",
      "utilities",
      "listrik",
      "telepon",
      "internet",
      "insurance",
      "asuransi",
      "repair and maintenance",
      "perbaikan",
      "pemeliharaan",
      "travel",
      "perjalanan dinas",
      "administrasi",
      "overhead",
      "bbm",
      "stnk",
      "pbb",
      "notaris",
      "kantor",
    ],
    excludeKeywords: ["bunga", "interest", "tax", "pajak penghasilan", "gain", "loss", "selisih kurs"],
    treatment: "operating",
    valuationImpact: ["EBIT", "DCF margin"],
    reviewNote: "Operating expense yang mengecualikan financing dan non-operating items.",
  },
  {
    category: "OPERATING_EXPENSE",
    displayName: "Operating Expense",
    aliases: [
      "operating expense",
      "operating expenses",
      "opex",
      "beban operasional",
      "biaya operasional",
      "beban operasi",
      "biaya operasi",
      "employee expense",
      "salary expense",
      "wages",
      "beban gaji",
      "biaya gaji",
      "upah",
      "research and development",
      "r&d expense",
      "amortization expense",
      "beban amortisasi",
    ],
    includeKeywords: [
      "operating expense",
      "operating expenses",
      "opex",
      "beban operasional",
      "biaya operasional",
      "beban operasi",
      "biaya operasi",
      "employee expense",
      "salary expense",
      "beban gaji",
      "biaya gaji",
      "wages",
      "upah",
      "research and development",
      "r&d",
      "amortization expense",
      "beban amortisasi",
    ],
    excludeKeywords: ["bunga", "interest", "tax", "pajak", "pokok", "cogs", "hpp"],
    treatment: "operating",
    valuationImpact: ["EBIT", "DCF margin"],
    reviewNote: "Operating expense broad category; gunakan kategori selling atau G&A yang lebih spesifik jika tersedia.",
  },
  {
    category: "EBIT",
    displayName: "EBIT",
    aliases: ["ebit", "earnings before interest and tax", "profit before interest and tax", "laba usaha", "operating profit", "laba operasi"],
    includeKeywords: ["ebit", "earnings before interest and tax", "profit before interest and tax", "laba usaha", "operating profit", "laba operasi"],
    treatment: "operating",
    valuationImpact: ["NOPLAT", "DCF"],
    reviewNote: "Gunakan commercial EBIT sebagai override ketika komponen income statement tidak lengkap.",
  },
  {
    category: "COMMERCIAL_NPAT",
    displayName: "Commercial NPAT",
    aliases: [
      "laba bersih komersial",
      "commercial npat",
      "net profit after tax",
      "profit for the year",
      "profit for the period",
      "laba setelah pajak",
      "laba bersih tahun berjalan",
      "laba bersih",
      "net income",
    ],
    includeKeywords: [
      "laba bersih komersial",
      "commercial npat",
      "net profit after tax",
      "profit for the year",
      "profit for the period",
      "laba setelah pajak",
      "laba bersih tahun berjalan",
      "laba bersih",
      "npat",
      "net profit",
      "net income",
    ],
    treatment: "operating",
    valuationImpact: ["earning power support", "retained earnings support"],
    reviewNote: "Gunakan commercial profit saja; jangan gunakan fiscal reconciliation sebagai earning power.",
  },
  {
    category: "CORPORATE_TAX",
    displayName: "Corporate Tax",
    aliases: [
      "corporate tax",
      "corporate income tax",
      "income tax expense",
      "tax expense",
      "current tax expense",
      "beban pajak",
      "beban pajak penghasilan",
      "pajak penghasilan badan",
      "pajak badan",
      "pajak kini",
      "pajak korporasi",
    ],
    includeKeywords: [
      "corporate tax",
      "corporate income tax",
      "income tax expense",
      "tax expense",
      "current tax expense",
      "beban pajak",
      "beban pajak penghasilan",
      "pajak penghasilan badan",
      "pajak badan",
      "pajak kini",
      "pajak korporasi",
    ],
    excludeKeywords: ["payable", "utang", "hutang", "terutang", "ppn", "vat"],
    treatment: "review",
    valuationImpact: ["income statement", "profit after tax bridge", "cash flow tax payment"],
    reviewNote: "Corporate tax adalah row Laba Rugi setelah Profit Before Tax; bukan pengganti statutory tax rate untuk NOPLAT valuasi.",
  },
  {
    category: "INTEREST_INCOME",
    displayName: "Interest Income",
    aliases: [
      "interest income",
      "finance income",
      "pendapatan bunga",
      "penghasilan bunga",
      "pendapatan keuangan",
      "penghasilan keuangan",
      "jasa giro",
      "bunga deposito",
      "pendapatan deposito",
      "penghasilan deposito",
      "bagi hasil bank",
    ],
    includeKeywords: [
      "interest income",
      "finance income",
      "pendapatan bunga",
      "penghasilan bunga",
      "pendapatan keuangan",
      "penghasilan keuangan",
      "jasa giro",
      "bunga deposito",
      "pendapatan deposito",
      "penghasilan deposito",
      "bagi hasil",
    ],
    excludeKeywords: ["beban", "expense", "biaya"],
    treatment: "non_operating",
    valuationImpact: ["NOPLAT exclusion", "surplus asset support"],
    reviewNote: "Keluarkan dari operating NOPLAT; dapat mendukung deposit sebagai surplus asset.",
  },
  {
    category: "INTEREST_EXPENSE",
    displayName: "Interest Expense",
    aliases: [
      "interest expense",
      "finance cost",
      "finance costs",
      "beban bunga",
      "biaya bunga",
      "beban keuangan",
      "biaya keuangan",
      "beban jasa giro",
      "beban pinjaman",
      "biaya pinjaman",
      "interest on lease liability",
      "bunga liabilitas sewa",
    ],
    includeKeywords: [
      "interest expense",
      "finance cost",
      "finance costs",
      "beban bunga",
      "biaya bunga",
      "beban keuangan",
      "biaya keuangan",
      "beban pinjaman",
      "biaya pinjaman",
      "interest on lease",
      "bunga liabilitas sewa",
    ],
    treatment: "financing",
    valuationImpact: ["NOPLAT exclusion", "debt review"],
    reviewNote: "Keluarkan dari operating NOPLAT dan tinjau apakah related debt tersedia.",
  },
  {
    category: "NON_OPERATING_INCOME",
    displayName: "Non Operating Income",
    aliases: [
      "non operating income",
      "non-operating income",
      "pendapatan lain-lain",
      "penghasilan lain-lain",
      "pendapatan lainnya",
      "penghasilan lainnya",
      "beban lain-lain",
      "biaya lain-lain",
      "other income",
      "other expense",
      "foreign exchange gain",
      "foreign exchange loss",
      "selisih kurs",
      "gain on disposal of fixed assets",
      "loss on disposal of fixed assets",
      "laba penjualan aset tetap",
      "rugi penjualan aset tetap",
      "fair value gain",
      "fair value loss",
      "impairment loss",
      "kerugian penurunan nilai",
      "dividend income",
      "pendapatan dividen",
    ],
    includeKeywords: [
      "non operating income",
      "non-operating income",
      "pendapatan lain",
      "penghasilan lain",
      "beban lain",
      "biaya lain",
      "other income",
      "other expense",
      "non operating",
      "foreign exchange",
      "selisih kurs",
      "gain on disposal",
      "loss on disposal",
      "penjualan aset tetap",
      "fair value",
      "nilai wajar",
      "impairment",
      "penurunan nilai",
      "dividend income",
      "pendapatan dividen",
    ],
    treatment: "non_operating",
    valuationImpact: ["NOPLAT exclusion", "CFI review"],
    reviewNote: "Keluarkan dari operating earning power.",
  },
  {
    category: "WORKING_CAPITAL",
    displayName: "Working Capital Support",
    aliases: ["working capital", "net working capital", "modal kerja", "modal kerja bersih", "operating working capital"],
    includeKeywords: ["working capital", "net working capital", "modal kerja", "modal kerja bersih", "operating working capital"],
    treatment: "review",
    valuationImpact: ["working capital support", "DCF WC days"],
    reviewNote: "Gunakan sebagai support/review; model tetap mengutamakan AR, inventory, AP, dan other payable sebagai driver WC.",
  },
  {
    category: "CASH_FLOW_FROM_OPERATIONS",
    displayName: "Cash Flow From Operations",
    aliases: [
      "cash flow from operations",
      "cash flows from operating activities",
      "arus kas dari aktivitas operasi",
      "arus kas operasi",
      "operating cash flow",
      "ocf",
    ],
    includeKeywords: [
      "cash flow from operations",
      "operating activities",
      "aktivitas operasi",
      "arus kas operasi",
      "operating cash flow",
      "ocf",
    ],
    treatment: "operating",
    valuationImpact: ["cash flow bridge", "DCF support"],
    reviewNote: "Gunakan sebagai support bridge; FCFF tetap dihitung dari EBIT, NOPLAT, dan operating WC.",
  },
  {
    category: "CASH_FLOW_FROM_FINANCING",
    displayName: "Cash Flow From Financing",
    aliases: [
      "cash flow from financing",
      "cash flows from financing activities",
      "arus kas dari aktivitas pendanaan",
      "arus kas pendanaan",
      "financing cash flow",
      "cfff",
    ],
    includeKeywords: ["cash flow from financing", "financing activities", "aktivitas pendanaan", "arus kas pendanaan", "financing cash flow"],
    treatment: "financing",
    valuationImpact: ["cash flow bridge", "debt and equity movement review"],
    reviewNote: "Gunakan untuk meninjau movement debt/equity; bukan driver operating FCFF langsung.",
  },
  {
    category: "CASH_FLOW_FROM_NON_OPERATIONS",
    displayName: "Cash Flow From Non-Operations",
    aliases: [
      "cash flow from investing",
      "cash flows from investing activities",
      "arus kas dari aktivitas investasi",
      "arus kas investasi",
      "cash flow from non operations",
      "arus kas non operasi",
    ],
    includeKeywords: [
      "cash flow from investing",
      "investing activities",
      "aktivitas investasi",
      "arus kas investasi",
      "cash flow from non operations",
      "arus kas non operasi",
    ],
    treatment: "non_operating",
    valuationImpact: ["cash flow bridge", "capex and non-operating asset review"],
    reviewNote: "Gunakan untuk meninjau capex, investasi, dan asset disposal; klasifikasi ulang jika merupakan operating capex support.",
  },
  {
    category: "CASH_FLOW_AVAILABLE_TO_INVESTOR",
    displayName: "Cash Flow Available To Investor",
    aliases: [
      "cash flow available to investor",
      "cash flow available to investors",
      "free cash flow to firm",
      "fcff",
      "free cash flow",
      "arus kas bebas",
      "arus kas tersedia untuk investor",
    ],
    includeKeywords: [
      "cash flow available to investor",
      "cash flow available to investors",
      "free cash flow to firm",
      "fcff",
      "free cash flow",
      "arus kas bebas",
      "tersedia untuk investor",
    ],
    treatment: "review",
    valuationImpact: ["DCF support", "cash flow bridge"],
    reviewNote: "Gunakan sebagai support/reconciliation terhadap FCFF hasil kalkulasi model.",
  },
];

export function normalizeAccountLabel(label: string): string {
  return label
    .toLowerCase()
    .replace(/\ba\s*\/\s*r\b/g, " account receivable ")
    .replace(/\ba\s*\/\s*p\b/g, " account payable ")
    .replace(/\bg\s*&\s*a\b/g, " general administrative ")
    .replace(/\br\s*&\s*d\b/g, " research and development ")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\binvt\b/g, "inventaris")
    .replace(/\binv\b/g, "inventaris")
    .replace(/\bppe\b/g, "property plant equipment")
    .replace(/\brou\b/g, "right of use")
    .replace(/\bcogs\b/g, "cost of goods sold")
    .replace(/\bhpp\b/g, "harga pokok penjualan")
    .replace(/\bnpat\b/g, "net profit after tax")
    .replace(/\bkmk\b/g, "kredit modal kerja")
    .replace(/\butg\b/g, "utang")
    .replace(/\bhtg\b/g, "hutang")
    .replace(/\bpiut\b/g, "piutang")
    .replace(/\bby\b/g, "biaya")
    .replace(/\s+/g, " ")
    .trim();
}

export function mapAccount(sourceLabel: string, statement?: StatementContext): AccountMappingResult {
  const normalizedLabel = normalizeAccountLabel(sourceLabel);

  if (!normalizedLabel) {
    return {
      sourceLabel,
      normalizedLabel,
      category: "UNMAPPED",
      displayName: "Unmapped",
      confidence: 0,
      confidenceBand: "none",
      treatment: "review",
      valuationImpact: ["mapping review"],
      reason: "Nama akun masih kosong.",
      needsReview: true,
      matchedKeywords: [],
      excludedKeywords: [],
      statementCompatible: statement ? false : null,
      alternatives: [],
    };
  }

  const scored = accountMappingRules.map((rule) => {
    const aliasMatches = rule.aliases.map(normalizeAccountLabel).filter((alias) => containsNormalizedPhrase(normalizedLabel, alias));
    const exactAliasHit = rule.aliases.some((alias) => normalizedLabel === normalizeAccountLabel(alias));
    const aliasHit = aliasMatches.length > 0;
    const matchedKeywords = rule.includeKeywords.filter((keyword) => containsNormalizedPhrase(normalizedLabel, keyword));
    const excludedKeywords = rule.excludeKeywords?.filter((keyword) => containsNormalizedPhrase(normalizedLabel, keyword)) ?? [];
    const includeHits = matchedKeywords.length;
    const excluded = excludedKeywords.length > 0;
    const statementCompatible = isStatementCompatible(rule.category, statement);
    const lexicalMatch = aliasHit || includeHits > 0;
    const specificityBoost = Math.min(longestPhraseLength(aliasMatches) * 0.04, 0.16);
    const includeScore = Math.min(matchedKeywords.reduce((sum, keyword) => sum + keywordMatchWeight(keyword), 0), 0.34);
    const rawScore = lexicalMatch
      ? (exactAliasHit ? 0.88 : aliasHit ? 0.62 : 0) +
        includeScore +
        specificityBoost -
        (excluded ? 0.62 : 0) +
        (statementCompatible === true ? 0.05 : 0) -
        (statementCompatible === false ? 0.62 : 0)
      : 0;

    return {
      rule,
      confidence: Math.max(0, Math.min(0.99, rawScore)),
      exactAliasHit,
      aliasHit,
      includeHits,
      excluded,
      matchedKeywords,
      excludedKeywords,
      lexicalMatch,
      statementCompatible,
    };
  });

  const ranked = scored.sort((a, b) => b.confidence - a.confidence);
  const best = ranked[0];
  const runnerUp = ranked.find((candidate) => candidate.rule.category !== best?.rule.category && candidate.confidence > 0);
  const confidence = best?.confidence ?? 0;
  const rule = best?.rule ?? accountMappingRules[0];
  const ambiguousMatch = Boolean(runnerUp && confidence >= 0.45 && confidence - runnerUp.confidence <= 0.12);

  if (!best || !best.lexicalMatch || confidence === 0) {
    return {
      sourceLabel,
      normalizedLabel,
      category: "UNMAPPED",
      displayName: "Unmapped",
      confidence: 0,
      confidenceBand: "none",
      treatment: "review",
      valuationImpact: ["mapping review"],
      reason: "Tidak ada alias atau keyword yang cocok. Tinjauan kategori manual diperlukan.",
      needsReview: true,
      matchedKeywords: [],
      excludedKeywords: [],
      statementCompatible: statement ? false : null,
      alternatives: buildAlternatives(ranked),
    };
  }

  return {
    sourceLabel,
    normalizedLabel,
    category: rule.category,
    displayName: rule.displayName,
    confidence,
    confidenceBand: confidenceBand(confidence),
    treatment: rule.treatment,
    valuationImpact: rule.valuationImpact,
    reason: `${best.exactAliasHit ? "Alias persis cocok" : best.aliasHit ? "Alias cocok" : "Keyword cocok"} dengan ${best.includeHits} keyword hit.${
      ambiguousMatch ? ` Kandidat lain dekat: ${runnerUp?.rule.displayName}.` : ""
    } ${best.excluded ? `Keyword dikecualikan: ${best.excludedKeywords.join(", ")}. ` : ""}${rule.reviewNote}`,
    needsReview: confidence < 0.72 || best.excluded || best.statementCompatible === false || ambiguousMatch,
    matchedKeywords: best.matchedKeywords,
    excludedKeywords: best.excludedKeywords,
    statementCompatible: best.statementCompatible,
    alternatives: buildAlternatives(ranked, rule.category),
  };
}

export function shouldAutoApplyMapping(mapping: AccountMappingResult): boolean {
  const runnerUp = mapping.alternatives[0];
  const hasComfortableLead = !runnerUp || mapping.confidence - runnerUp.confidence > 0.12;

  return (
    mapping.category !== "UNMAPPED" &&
    mapping.confidenceBand === "high" &&
    mapping.confidence >= 0.82 &&
    mapping.statementCompatible !== false &&
    !mapping.needsReview &&
    hasComfortableLead
  );
}

function containsNormalizedPhrase(label: string, phrase: string): boolean {
  const normalizedPhrase = normalizeAccountLabel(phrase);

  if (!normalizedPhrase) {
    return false;
  }

  return ` ${label} `.includes(` ${normalizedPhrase} `);
}

function longestPhraseLength(phrases: string[]): number {
  return phrases.reduce((longest, phrase) => Math.max(longest, phrase.split(" ").length - 1), 0);
}

function keywordMatchWeight(keyword: string): number {
  const wordCount = normalizeAccountLabel(keyword).split(" ").filter(Boolean).length;

  if (wordCount >= 3) {
    return 0.13;
  }

  if (wordCount === 2) {
    return 0.1;
  }

  return 0.055;
}

function confidenceBand(confidence: number): AccountMappingResult["confidenceBand"] {
  if (confidence >= 0.82) {
    return "high";
  }

  if (confidence >= 0.64) {
    return "medium";
  }

  if (confidence > 0) {
    return "low";
  }

  return "none";
}

function buildAlternatives(
  candidates: Array<{ rule: AccountMappingRule; confidence: number; lexicalMatch: boolean }>,
  excludedCategory?: string,
): AccountMappingResult["alternatives"] {
  return candidates
    .filter((candidate) => candidate.lexicalMatch && candidate.confidence > 0 && candidate.rule.category !== excludedCategory)
    .slice(0, 3)
    .map((candidate) => ({
      category: candidate.rule.category,
      displayName: candidate.rule.displayName,
      confidence: candidate.confidence,
      treatment: candidate.rule.treatment,
    }));
}

function isStatementCompatible(category: string, statement?: StatementContext): boolean | null {
  if (!statement) {
    return null;
  }

  if (statementAgnosticCategories.has(category)) {
    return null;
  }

  if (statement === "balance_sheet") {
    return balanceSheetCategories.has(category);
  }

  if (statement === "income_statement") {
    return incomeStatementCategories.has(category);
  }

  return fixedAssetCategories.has(category);
}
