import type { StatementType } from "./case-model";
import type { AccountCategory } from "./types";

export const categoryOptions: Array<{ value: AccountCategory; label: string }> = [
  { value: "UNMAPPED", label: "Perlu ditinjau / belum dipetakan" },
  { value: "TOTAL_ASSETS", label: "Total assets override" },
  { value: "CURRENT_ASSET", label: "Current asset - broad" },
  { value: "CASH_ON_HAND", label: "Cash on hand / kas" },
  { value: "CASH_ON_BANK", label: "Cash on bank / deposit" },
  { value: "ACCOUNT_RECEIVABLE", label: "Account receivable" },
  { value: "EMPLOYEE_RECEIVABLE", label: "Employee / related-party receivable" },
  { value: "INVENTORY", label: "Inventory" },
  { value: "FIXED_ASSET", label: "Fixed asset net value" },
  { value: "FIXED_ASSET_ACQUISITION", label: "Fixed asset acquisition cost" },
  { value: "ACCUMULATED_DEPRECIATION", label: "Accumulated depreciation" },
  { value: "INTANGIBLE_ASSETS", label: "Intangible assets" },
  { value: "NON_CURRENT_ASSET", label: "Non-current asset - broad" },
  { value: "TOTAL_LIABILITIES", label: "Total liabilities override" },
  { value: "CURRENT_LIABILITIES", label: "Current liabilities - broad" },
  { value: "BANK_LOAN_SHORT_TERM", label: "Bank loan - short term" },
  { value: "ACCOUNT_PAYABLE", label: "Account payable" },
  { value: "TAX_PAYABLE", label: "Tax payable" },
  { value: "OTHER_PAYABLE", label: "Other payable" },
  { value: "BANK_LOAN_LONG_TERM", label: "Bank loan - long term" },
  { value: "NON_CURRENT_LIABILITIES", label: "Non-current liabilities - broad" },
  { value: "MODAL_DISETOR", label: "Modal disetor" },
  { value: "PENAMBAHAN_MODAL_DISETOR", label: "Penambahan modal disetor" },
  { value: "RETAINED_EARNINGS_SURPLUS", label: "Retained earnings surplus" },
  { value: "RETAINED_EARNINGS_CURRENT_PROFIT", label: "Retained earnings current profit" },
  { value: "REVENUE", label: "Revenue" },
  { value: "COST_OF_GOOD_SOLD", label: "Cost of goods sold" },
  { value: "SELLING_EXPENSE", label: "Selling expense" },
  { value: "GENERAL_ADMINISTRATIVE_OVERHEADS", label: "General & administrative expense" },
  { value: "OPERATING_EXPENSE", label: "Operating expense - other" },
  { value: "DEPRECIATION_EXPENSE", label: "Depreciation expense" },
  { value: "EBIT", label: "Commercial EBIT override" },
  { value: "COMMERCIAL_NPAT", label: "Commercial NPAT" },
  { value: "INTEREST_INCOME", label: "Interest income" },
  { value: "INTEREST_EXPENSE", label: "Interest expense" },
  { value: "NON_OPERATING_INCOME", label: "Non-operating income / expense" },
  { value: "NON_OPERATING_FIXED_ASSETS", label: "Non-operating fixed assets" },
  { value: "EXCESS_CASH", label: "Excess cash" },
  { value: "MARKETABLE_SECURITIES", label: "Marketable securities" },
  { value: "INTEREST_PAYABLE", label: "Interest payable" },
  { value: "INTEREST_BEARING_DEBT", label: "Interest-bearing debt" },
  { value: "SURPLUS_ASSET_CASH", label: "Surplus asset cash" },
  { value: "WORKING_CAPITAL", label: "Working capital support" },
  { value: "CASH_FLOW_FROM_FINANCING", label: "Cash flow from financing" },
  { value: "CASH_FLOW_FROM_OPERATIONS", label: "Cash flow from operations" },
  { value: "CASH_FLOW_FROM_NON_OPERATIONS", label: "Cash flow from non-operations" },
  { value: "CASH_FLOW_AVAILABLE_TO_INVESTOR", label: "Cash flow available to investor" },
];

export const categoryLabelMap = new Map(categoryOptions.map((option) => [option.value, option.label]));

export const categoryOptionsByStatement: Record<StatementType, Set<AccountCategory>> = {
  balance_sheet: new Set([
    "UNMAPPED",
    "TOTAL_ASSETS",
    "CURRENT_ASSET",
    "CASH_ON_HAND",
    "CASH_ON_BANK",
    "ACCOUNT_RECEIVABLE",
    "EMPLOYEE_RECEIVABLE",
    "INVENTORY",
    "FIXED_ASSET",
    "FIXED_ASSET_ACQUISITION",
    "ACCUMULATED_DEPRECIATION",
    "INTANGIBLE_ASSETS",
    "NON_CURRENT_ASSET",
    "TOTAL_LIABILITIES",
    "CURRENT_LIABILITIES",
    "BANK_LOAN_SHORT_TERM",
    "ACCOUNT_PAYABLE",
    "TAX_PAYABLE",
    "OTHER_PAYABLE",
    "BANK_LOAN_LONG_TERM",
    "NON_CURRENT_LIABILITIES",
    "MODAL_DISETOR",
    "PENAMBAHAN_MODAL_DISETOR",
    "RETAINED_EARNINGS_SURPLUS",
    "RETAINED_EARNINGS_CURRENT_PROFIT",
    "NON_OPERATING_FIXED_ASSETS",
    "EXCESS_CASH",
    "MARKETABLE_SECURITIES",
    "INTEREST_PAYABLE",
    "INTEREST_BEARING_DEBT",
    "SURPLUS_ASSET_CASH",
  ]),
  income_statement: new Set([
    "UNMAPPED",
    "REVENUE",
    "COST_OF_GOOD_SOLD",
    "SELLING_EXPENSE",
    "GENERAL_ADMINISTRATIVE_OVERHEADS",
    "OPERATING_EXPENSE",
    "DEPRECIATION_EXPENSE",
    "EBIT",
    "COMMERCIAL_NPAT",
    "INTEREST_INCOME",
    "INTEREST_EXPENSE",
    "NON_OPERATING_INCOME",
  ]),
  fixed_asset: new Set(["UNMAPPED", "FIXED_ASSET", "FIXED_ASSET_ACQUISITION", "ACCUMULATED_DEPRECIATION", "DEPRECIATION_EXPENSE"]),
};
