import type { StatementType } from "./case-model";
import type { AccountCategory } from "./types";

export const categoryOptions: Array<{ value: AccountCategory; label: string }> = [
  { value: "UNMAPPED", label: "Perlu ditinjau / belum dipetakan" },
  { value: "TOTAL_ASSETS", label: "Total aset (override)" },
  { value: "CURRENT_ASSET", label: "Aset lancar - umum" },
  { value: "CASH_ON_HAND", label: "Kas di tangan (cash on hand)" },
  { value: "CASH_ON_BANK", label: "Bank dan deposito" },
  { value: "ACCOUNT_RECEIVABLE", label: "Piutang usaha" },
  { value: "EMPLOYEE_RECEIVABLE", label: "Piutang karyawan / pihak berelasi" },
  { value: "INVENTORY", label: "Persediaan" },
  { value: "FIXED_ASSET", label: "Nilai buku aset tetap" },
  { value: "FIXED_ASSET_ACQUISITION", label: "Harga perolehan aset tetap" },
  { value: "ACCUMULATED_DEPRECIATION", label: "Akumulasi penyusutan" },
  { value: "INTANGIBLE_ASSETS", label: "Aset tak berwujud" },
  { value: "NON_CURRENT_ASSET", label: "Aset tidak lancar - umum" },
  { value: "TOTAL_LIABILITIES", label: "Total liabilitas (override)" },
  { value: "CURRENT_LIABILITIES", label: "Liabilitas lancar - umum" },
  { value: "BANK_LOAN_SHORT_TERM", label: "Pinjaman bank jangka pendek" },
  { value: "ACCOUNT_PAYABLE", label: "Utang usaha" },
  { value: "TAX_PAYABLE", label: "Utang pajak" },
  { value: "OTHER_PAYABLE", label: "Utang lain-lain" },
  { value: "BANK_LOAN_LONG_TERM", label: "Pinjaman bank jangka panjang" },
  { value: "NON_CURRENT_LIABILITIES", label: "Liabilitas tidak lancar - umum" },
  { value: "MODAL_DISETOR", label: "Modal disetor" },
  { value: "PENAMBAHAN_MODAL_DISETOR", label: "Penambahan modal disetor" },
  { value: "RETAINED_EARNINGS_SURPLUS", label: "Saldo laba ditahan" },
  { value: "RETAINED_EARNINGS_CURRENT_PROFIT", label: "Laba tahun berjalan di neraca" },
  { value: "REVENUE", label: "Pendapatan usaha (revenue)" },
  { value: "COST_OF_GOOD_SOLD", label: "Beban pokok penjualan" },
  { value: "SELLING_EXPENSE", label: "Beban penjualan" },
  { value: "GENERAL_ADMINISTRATIVE_OVERHEADS", label: "Beban umum dan administrasi" },
  { value: "OPERATING_EXPENSE", label: "Beban operasional lain" },
  { value: "DEPRECIATION_EXPENSE", label: "Beban penyusutan" },
  { value: "EBIT", label: "EBIT komersial (override)" },
  { value: "COMMERCIAL_NPAT", label: "NPAT komersial" },
  { value: "CORPORATE_TAX", label: "Pajak penghasilan badan" },
  { value: "INTEREST_INCOME", label: "Pendapatan bunga" },
  { value: "INTEREST_EXPENSE", label: "Beban bunga" },
  { value: "NON_OPERATING_INCOME", label: "Pendapatan / beban non-operasional" },
  { value: "NON_OPERATING_FIXED_ASSETS", label: "Aset tetap non-operasional" },
  { value: "EXCESS_CASH", label: "Kas berlebih" },
  { value: "MARKETABLE_SECURITIES", label: "Surat berharga" },
  { value: "INTEREST_PAYABLE", label: "Utang bunga" },
  { value: "INTEREST_BEARING_DEBT", label: "Utang berbunga" },
  { value: "SURPLUS_ASSET_CASH", label: "Kas aset surplus" },
  { value: "WORKING_CAPITAL", label: "Dukungan modal kerja (working capital)" },
  { value: "CASH_FLOW_FROM_FINANCING", label: "Arus kas dari pendanaan" },
  { value: "CASH_FLOW_FROM_OPERATIONS", label: "Arus kas dari operasi" },
  { value: "CASH_FLOW_FROM_NON_OPERATIONS", label: "Arus kas non-operasional" },
  { value: "CASH_FLOW_AVAILABLE_TO_INVESTOR", label: "Arus kas tersedia untuk investor" },
];

export const categoryLabelMap = new Map(categoryOptions.map((option) => [option.value, option.label]));

export const categoryOptionsByStatement: Record<StatementType, Set<AccountCategory>> = {
  balance_sheet: new Set([
    "UNMAPPED",
    "TOTAL_ASSETS",
    "CURRENT_ASSET",
    "CASH_ON_HAND",
    "CASH_ON_BANK",
    "ACCOUNT_RECEIVABLE",
    "EMPLOYEE_RECEIVABLE",
    "INVENTORY",
    "FIXED_ASSET",
    "FIXED_ASSET_ACQUISITION",
    "ACCUMULATED_DEPRECIATION",
    "INTANGIBLE_ASSETS",
    "NON_CURRENT_ASSET",
    "TOTAL_LIABILITIES",
    "CURRENT_LIABILITIES",
    "BANK_LOAN_SHORT_TERM",
    "ACCOUNT_PAYABLE",
    "TAX_PAYABLE",
    "OTHER_PAYABLE",
    "BANK_LOAN_LONG_TERM",
    "NON_CURRENT_LIABILITIES",
    "MODAL_DISETOR",
    "PENAMBAHAN_MODAL_DISETOR",
    "RETAINED_EARNINGS_SURPLUS",
    "RETAINED_EARNINGS_CURRENT_PROFIT",
    "NON_OPERATING_FIXED_ASSETS",
    "EXCESS_CASH",
    "MARKETABLE_SECURITIES",
    "INTEREST_PAYABLE",
    "INTEREST_BEARING_DEBT",
    "SURPLUS_ASSET_CASH",
  ]),
  income_statement: new Set([
    "UNMAPPED",
    "REVENUE",
    "COST_OF_GOOD_SOLD",
    "SELLING_EXPENSE",
    "GENERAL_ADMINISTRATIVE_OVERHEADS",
    "OPERATING_EXPENSE",
    "DEPRECIATION_EXPENSE",
    "EBIT",
    "COMMERCIAL_NPAT",
    "CORPORATE_TAX",
    "INTEREST_INCOME",
    "INTEREST_EXPENSE",
    "NON_OPERATING_INCOME",
  ]),
  fixed_asset: new Set(["UNMAPPED", "FIXED_ASSET", "FIXED_ASSET_ACQUISITION", "ACCUMULATED_DEPRECIATION", "DEPRECIATION_EXPENSE"]),
};
